name: Java CI

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Fix build - Remove desktop simulation
      run: sed -i -e 's/def includeDesktopSupport = true/def includeDesktopSupport = false/' -e '/nativeDesktopZip/d' build.gradle
    
    - name: Download Dependencies
      run: ./gradlew downloadDepsPreemptively downloadAll --info
    
    - name: Check for formatting
      run: ./gradlew spotlessCheck --info
    
    - name: Build with Gradle
      run: ./gradlew build --info
